<?php
if (!defined("BASEPATH")) exit("No direct script access allowed");
$config["sitename"] = 'SharpEdge';
$config["site_slogan"] = 'Performance &amp; Control';
$config["contact_email"] = 'sales@purdydesigns.com';
$config["homepage_string"] = 'Home-Page';
$config["short_url"] = true;
$config["google_stats"] = false;
$config["google_id"] = '';
$config["twitter"] = false;
$config["facebook"] = false;
$config["linkedin"] = false;
$config["twitter_url"] = '';
$config["facebook_url"] = '';
$config["linkedin_url"] = '';
$config["construction"] = false;
$config["allow_register"] = true;
$config["security_register"] = 'I';
$config["robots"] = 'index, follow';
$config["description"] = 'Description';
$config["keywords"] = 'Keywords';
$config["image_src"] = 'logo.png';
$config["benchmark"] = false;
$config["themes_url"] = 'http://themes.yourdomain.com/';
$config["assets_url"] = 'http://assets.yourdomain.com/';
$config["gallery_url"] = 'http://gallery.yourdomain.com/';
$config["global_upload_limit"] = '20000';
$config["global_upload_maxwidth"] = '5000';
$config["global_upload_maxheight"] = '5000';
$config["global_filetypes"] = 'jpg|jpeg|gif|png';
$config["copyright"] = '&copy; 2008-2014 NewEdge Development All Rights Reserved';
$config["generator"] = 'SharpEdge Version 3.39.12 By NewEdge Development & Omega Communications';
?>