----Running SharpEdge Updater----<br />
 - <?php echo $downloading;?><br />
 - <?php echo $checksum_process;?><br />
 - <?php echo $checksum;?><br />
 - <?php echo $make_temp;?><br />
 - <?php echo $extract;?><br />
 - <?php echo $copy_process;?><br />
 - <?php echo $database_update;?><br />
 - <?php echo $deleted_files?><br />
---------------------------------<br />
<?php echo $summary;?>